# Generated by Django 5.0.4 on 2024-05-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_porta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='viviendas',
            new_name='vivienda',
        ),
    ]
