# Generated by Django 5.0.4 on 2024-05-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_porta', '0003_alter_vivienda_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='fechaTermino',
            field=models.DateField(),
        ),
    ]
