# Generated by Django 5.0.4 on 2024-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_porta', '0005_remove_vivienda_tipovivienda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='tipoVivienda',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
    ]
