# Generated by Django 5.0.4 on 2024-05-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_porta', '0010_alter_vivienda_baños_alter_vivienda_habitaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='baños',
        ),
        migrations.RemoveField(
            model_name='vivienda',
            name='habitaciones',
        ),
    ]
