# Generated by Django 5.0.4 on 2024-05-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_porta', '0011_remove_vivienda_baños_remove_vivienda_habitaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='baños',
            field=models.IntegerField(default=0),
        ),
    ]
