# Generated by Django 5.0.4 on 2024-05-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_porta', '0012_vivienda_baños'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vivienda',
            old_name='baños',
            new_name='baño',
        ),
    ]
