# Generated by Django 5.0.4 on 2024-05-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_porta', '0013_rename_baños_vivienda_baño'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='baño',
        ),
    ]
