# Generated by Django 5.0.4 on 2024-05-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_porta', '0014_remove_vivienda_baño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='imagen',
            field=models.CharField(max_length=200),
        ),
    ]
